#include "RGBkeyboard.h"

KeyboardKeycode key_layer_1[20] = {
	KEY_1,KEY_2,KEY_3,KEY_4,
	KEY_Q,KEY_W,KEY_E,KEY_R,
	KEY_A,KEY_S,KEY_D,KEY_F,
	KEY_Z,KEY_B,KEY_LEFT_SHIFT,KEY_SPACE,
	KEY_FN,KEY_5,KEY_TAB,KEY_LEFT_CTRL
};


KeyboardKeycode key_layer_2[20] = {
	KEY_NUM_LOCK,KEYPAD_DIVIDE,KEYPAD_MULTIPLY,KEYPAD_SUBTRACT,
	KEYPAD_7,KEYPAD_8,KEYPAD_9,KEYPAD_ADD,
	KEYPAD_4,KEYPAD_5,KEYPAD_6,KEY_BACKSPACE,
	KEYPAD_1,KEYPAD_2,KEYPAD_3,KEY_TAB,
	KEY_FN,KEYPAD_0,KEYPAD_DOT,KEY_RETURN
};
